install.packages("tidyverse")
library(dplyr)
MechaCar_mpg <- read.csv(file = 'MechaCar_mpg.csv',check.names=F, stringsAsFactors=F)
lm(mpg ~ vehicle_length + vehicle_weight + spoiler_angle + ground_clearance + AWD,data=MechaCar_mpg)
summary(lm(mpg ~ vehicle_length + vehicle_weight + spoiler_angle + ground_clearance + AWD,data=MechaCar_mpg)
)

Suspension_Coil <- read.csv(file = 'Suspension_Coil.csv',check.names=F, stringsAsFactors=F)
total_summary<- Suspension_Coil %>% summarise(Mean=mean(PSI), Median=median(PSI), Variance=var(PSI), SD=sd(PSI))
lot_summary<- Suspension_Coil %>% group_by(Manufacturing_Lot)%>% summarise(Mean=mean(PSI), Median=median(PSI), Variance=var(PSI), SD=sd(PSI))
t.test(log10(lot_summary$Mean),mu=mean (log10(total_summary$Mean)))
t.test(Suspension_Coil$PSI, mu=1500)
t.test(subset(Suspension_Coil,Manufacturing_Lot=="Lot1")$PSI,mu = 1500)
t.test(subset(Suspension_Coil,Manufacturing_Lot=="Lot2")$PSI,mu = 1500)
t.test(subset(Suspension_Coil,Manufacturing_Lot=="Lot3")$PSI,mu = 1500)

