install.packages("tidyverse")
library(dplyr)
csv.read(MechaCar_mpg.csv)
read.csv(MechaCar_mpg.csv)
MechaCar_mpg <- read.csv(file = 'MechaCar_mpg.csv',check.names=F, stringsAsFactors=F)
lm(mpg ~ vehicle_length + vehicle_weight + spoiler_angle + ground_clearance + AWD,data=MechaCar_mpg)
summary(lm(mpg ~ vehicle_length + vehicle_weight + spoiler_angle + ground_clearance + AWD,data=MechaCar_mpg)
)
